### ISSUE TITLE
Team forking?

### ISSUE THREAD

**Issue by ironfist** [githubteacher/advanced-apr-2015#10]
We have Enterprise GitHub. How can we control who commits to master?  It seems we can use fork + pull request, but that seems geared towards an individual.  How can a team work on a forked repo if the forked repo is in an individual's account?

Can you please explain?

**Comment by ironfist** [comment]
FYI we asked this on Tuesday but it was not revisited.

**Comment by ironfist** [comment]
Really, we just want multiple people to work on a feature, but not necessarily be able to commit to master.

**Comment by githubteacher** [comment]
@ironfist Apologies for not getting to this question yesterday. There are no branch-level permissions, so you're correct that a fork and pull request model is best. Most people have a canonical repo that all devs must fork. However, the other route is to have your team leads fork the main repo (which everyone works on), and then make this fork the canonical or prod version. Since the team leads are presumably small in number, they should be able to manage adding each other as collaborators to this fork.

Does that help?

**Comment by ironfist** [comment]
Ok, thanks.  Let's say we have org1/greatproject repo.  We have users fred (team lead), sam, and joe.  sam and joe need to work on feature1 on greatproject.  sam is going to fork greatproject, but it will go to sam/greatproject (in his account).  How does joe work on this?  Or am I missing something?

**Comment by githubteacher** [comment]
@ironfist So I was actually suggesting that Sam and Joe both do their work on the org1/greatproject repo. Fred forks that to get fred/greatproject, and uses that as the canonical repo.

In the scenario you described, Sam can of course add Joe as a collaborator to give the latter write access.

**Comment by ironfist** [comment]
Can you clarify what you mean by canonical repo?  Maybe I'm misunderstanding.

At the end of the day, we want to prevent sam and joe (poor, lowly developers, not team lead) access to master on org1/greatproject.  That's our prod/stable code and we don't want lowly developers to commit to it.  Obviously there's no branch-level security in GitHub so we have to work with the fork/pull-request workflow.

**Comment by githubteacher** [comment]
@ironfist Ah, sorry for the confusing language. I understand your situation exactly, and was just using the word canonical as a synonym for prod/stable. So in the model I suggested above, Fred will create a fork that will act as the repo for prod/stable code. He can merge changes from org1/greatprojectrepo's master branch into his fork's master, once he determines it's suitable for production. Fred could make sure that Joe and Sam do not have write access to his fork, precisely b/c it is the prod/stable version of greatproject.

**Comment by ironfist** [comment]
So you're saying **org1**/greatproject is basically just the sandbox version of "greatproject", correct?

But if **fred**/greatproject is the fork (and the "stable" version), that seems backwards to me.  It's accessed-controlled -- but doesn't that eliminate pull requests?  Because **org1** is the fork source, and that repo would fulfill the pull requests from **fred**.

I guess it seems backwards.  It seems more intuitive to have **org1**/greatproject as the stable version because a) it should be the org's repo, not an individual's, and b) there's no pull requests.

Help me understand :smile:

**Comment by paulcr** [comment]
I'm in a very similar situation in my organization so more info would be appreciated :+1:

**Comment by githubteacher** [comment]
@ironfist @paulcr  It is "backwards" in the sense that this is opposite the common approach, i.e. having devs' forks be the sandboxes. 

You could also "reverse the parentage." Have fred/project as the stable version, then set up an org/project fork as the sandbox. That way the sandbox doesn't have to be owned by a single dev.

In either case, devs can still open PRs from the sandbox to the prod version, even if they have only read access to the latter.

If you do want to keep the org/project as the prod version, i.e. follow what I called "common approach" above, you can have a chosen dev own the sandbox fork. The dev can just add other devs as collaborators to their fork, to give them write access. 

Another frequent approach is to have every dev create a personal fork, and add each other's forks as remotes (`git remote add sam-fork <url>`) as needed. That way they can open PRs both onto org/project and each other's forks, which can be useful.

**Comment by ironfist** [comment]
Gotcha, thanks.
