### ISSUE TITLE
Is there any way to lock down a tag (say one used for a build release)?

### ISSUE THREAD

**Issue by aalten** [githubteacher/advanced-apr-2015#14]
Can a tag only be modified/moved/deleted by a specific user?

**Comment by pcharlan** [comment]
You will host an "official" copy of your project somewhere; you would configure the system that controls access to that copy to reject changes/deletions to whatever refs or paths that you want.  How to configure that depends on what you use for access control to that repository.  Gitolite is one way I've used, but GitHub is another you may use :) and I'm sure it has a way to control who (if anyone) may modify or delete refs or paths in a project.

Git itself doesn't have a way: as a user with your own copy of the repository, you may modify it however you want.  (Though you may use hooks to make it harder to shoot yourself in the foot.)

**Comment by pcharlan** [comment]
I would add that you can write a custom update hook at the official repo to enforce whatever policy you want; it's a very flexible mechanism.

**Comment by aalten** [comment]
OK.  Sounds like two good approaches thanks.
@githubteacher 
@pcharlan
