### ISSUE TITLE
Difference between gitignore and excludes and when to use which

### ISSUE THREAD

**Issue by srikanthchitipotu** [githubteacher/advanced-apr-2015#16]

**Comment by pcharlan** [comment]
Use .gitignore for things that are inherent to the project or useful to anyone who interacts with it (e.g., ignore *.o or *.pyc files).  Use excludes for things that are specific to you (e.g., the editor you use likes to create backup files like "foo~") that nobody else in the project would care about.

**Comment by srikanthchitipotu** [comment]
:+1:
