### ISSUE TITLE
Is the content of a blob always the contents of the whole file?

### ISSUE THREAD

**Issue by rogernolan** [githubteacher/advanced-apr-2015#9]

**Comment by pcharlan** [comment]
If it's a file, the sha1 of the blob is the sha1 of the entire contents.  You can also have blobs that are symlinks, in which case it's the sha1 of the pathname that the symlink points to.

**Comment by githubstudent** [comment]
Under most circumstances, the blog contents are the entire file contents. Symlinks is a good example where that's not the case. 

Also there are plugins like [git-lfs](https://github.com/github/git-lfs) which are intended to make it easier to work with large files in git, by storing the file contents in some other service and only storing a pointer in git. But that's a fairly advanced case.
